### ISSUE TITLE
Unable to install gauge during CI build

### ISSUE THREAD

**Issue by code-aspirant** [getgauge/gauge#1984]
**Describe the bug**
Pipelines have started failing during the installation of gauge onto the image. This first occurred on May 2nd, 2021.

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Attempt to install gauge on a Bitbucket Pipeline Image

**Original pipeline:**
```yaml
pipelines:
  default:
    - step:
        image: maven:3.6.3-jdk-11
        name: UI Test
        caches:
          - maven
          - mavenwrapper
        script:
          - apt-get update && apt-get install -q -y apt-transport-https gnupg2 ca-certificates
          - apt-key adv --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys 023EDB0B
          - echo deb https://dl.bintray.com/gauge/gauge-deb stable main | tee -a /etc/apt/sources.list
          - apt-get update && apt-get install gauge
          - gauge install java && gauge install html-report && gauge install screenshot
          - gauge -v
          - chmod +x ./ci/maven-test.sh
          - ./ci/maven-test.sh
        after-script:
          - FOLDER=$(ls reports/html-report -t | head -n1)
          - echo $FOLDER
          - chmod +x ./ci/slack-notify.sh
          - ./ci/slack-notify.sh $BITBUCKET_EXIT_CODE "$FOLDER"
          - pipe: atlassian/azure-storage-deploy:1.0.1
            variables:
              SOURCE: 'reports/html-report/*'
              DESTINATION: 'redacted'
              DESTINATION_SAS_TOKEN: redacted
              EXTRA_ARGS: '--recursive'
              DEBUG: 'true'
        services:
          - chrome
        artifacts:
          - reports/html-report/**
definitions:
  caches:
    mavenwrapper: ~/.mvn/wrapper
  services:
    chrome:
      image: selenium/standalone-chrome
      environment:
        port: "4444"
```

**Pipeline Error Logs for original pipeline script (using apt-key):**

```
+ ./ci/install-gauge.sh
Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [285 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [10.9 kB]
Fetched 8441 kB in 2s (5412 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
ca-certificates is already the newest version (20200601~deb10u2).
The following NEW packages will be installed:
  apt-transport-https gnupg2
0 upgraded, 2 newly installed, 0 to remove and 5 not upgraded.
Need to get 542 kB of archives.
After this operation, 566 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster-updates/main amd64 apt-transport-https all 1.8.2.3 [149 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 gnupg2 all 2.2.12-1+deb10u1 [393 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 542 kB in 0s (45.3 MB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 12572 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.8.2.3_all.deb ...
Unpacking apt-transport-https (1.8.2.3) ...
Selecting previously unselected package gnupg2.
Preparing to unpack .../gnupg2_2.2.12-1+deb10u1_all.deb ...
Unpacking gnupg2 (2.2.12-1+deb10u1) ...
Setting up gnupg2 (2.2.12-1+deb10u1) ...
Setting up apt-transport-https (1.8.2.3) ...
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.p5K9kz4IIi/gpg.1.sh --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys 023EDB0B
gpg: key 25CCDC10023EDB0B: public key "gauge (gpg key for maven archetypes) <getgauge@thoughtworks.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
deb https://dl.bintray.com/gauge/gauge-deb stable main
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://deb.debian.org/debian buster-updates InRelease
Hit:3 http://security.debian.org/debian-security buster/updates InRelease
Err:4 https://dl.bintray.com/gauge/gauge-deb stable InRelease
  403  Forbidden [IP: 34.214.237.80 443]
Reading package lists...
E: Failed to fetch https://dl.bintray.com/gauge/gauge-deb/dists/stable/InRelease  403  Forbidden [IP: 34.214.237.80 443]
E: The repository 'https://dl.bintray.com/gauge/gauge-deb stable InRelease' is not signed.
./ci/install-gauge.sh: line 7: gauge: command not found
./ci/install-gauge.sh: line 8: gauge: command not found
```

* I first updated the installation script to match what is described here: https://docs.gauge.org/getting_started/installing-gauge.html?os=linux&language=java&ide=vscode. I also moved out the install logic to a separate .sh file

**Updated Pipeline:**
```yaml
pipelines:
  default:
    - step:
        image: maven:3.6.3-jdk-11
        name: UI Test
        caches:
          - maven
          - mavenwrapper
        script:
          - chmod +x ./ci/install-gauge.sh
          - chmod +x ./ci/maven-test.sh
          - ./ci/install-gauge.sh
          - ./ci/maven-test.sh
        after-script:
          - FOLDER=$(ls reports/html-report -t | head -n1)
          - echo $FOLDER
          - chmod +x ./ci/slack-notify.sh
          - ./ci/slack-notify.sh $BITBUCKET_EXIT_CODE "$FOLDER"
          - pipe: atlassian/azure-storage-deploy:1.0.1
            variables:
              SOURCE: 'reports/html-report/*'
              DESTINATION: 'redacted'
              DESTINATION_SAS_TOKEN: redacted
              EXTRA_ARGS: '--recursive'
              DEBUG: 'true'
        services:
          - chrome
        artifacts:
          - reports/html-report/**
definitions:
  caches:
    mavenwrapper: ~/.mvn/wrapper
  services:
    chrome:
      image: selenium/standalone-chrome
      environment:
        port: "4444"
``` 
**Install script ./ci/install-gauge.sh:**

```bash
#!/usr/bin/env bash

apt-get update && apt-get install -q -y apt-transport-https gnupg2 ca-certificates
gpg --no-default-keyring --keyring /usr/share/keyrings/gauge-archive-keyring.gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
bash -c "echo deb [signed-by=/usr/share/keyrings/gauge-archive-keyring.gpg] https://dl.bintray.com/gauge/gauge-deb stable main > /etc/apt/sources.list.d/gauge.list"
apt-get update && apt-get install gauge
gauge install java && gauge install html-report && gauge install screenshot
gauge -v
```

**Pipeline Error logs for updated script (using gpg):**
```
build : docker.io/library/maven@sha256:1d29ccf46ef2a5e64f7de3d79a63f9bcffb4dc56be0ae3daed5ca5542b38aa2d
+ chmod +x ./ci/install-gauge.sh
+ chmod +x ./ci/maven-test.sh
+ ./ci/install-gauge.sh
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [121 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [285 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [10.9 kB]
Fetched 8441 kB in 2s (5098 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
ca-certificates is already the newest version (20200601~deb10u2).
The following NEW packages will be installed:
  apt-transport-https gnupg2
0 upgraded, 2 newly installed, 0 to remove and 5 not upgraded.
Need to get 542 kB of archives.
After this operation, 566 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster-updates/main amd64 apt-transport-https all 1.8.2.3 [149 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 gnupg2 all 2.2.12-1+deb10u1 [393 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 542 kB in 0s (18.0 MB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 12572 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.8.2.3_all.deb ...
Unpacking apt-transport-https (1.8.2.3) ...
Selecting previously unselected package gnupg2.
Preparing to unpack .../gnupg2_2.2.12-1+deb10u1_all.deb ...
Unpacking gnupg2 (2.2.12-1+deb10u1) ...
Setting up gnupg2 (2.2.12-1+deb10u1) ...
Setting up apt-transport-https (1.8.2.3) ...
gpg: keybox '/usr/share/keyrings/gauge-archive-keyring.gpg' created
gpg: failed to create temporary file '/root/.gnupg/.#lk0x000055a61aa98e10.922ac0a6-411b-4c74-8d5b-cd658c464217-4pw59.334': No such file or directory
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Err:4 https://dl.bintray.com/gauge/gauge-deb stable InRelease
  403  Forbidden [IP: 52.40.89.93 443]
Reading package lists...
E: Failed to fetch https://dl.bintray.com/gauge/gauge-deb/dists/stable/InRelease  403  Forbidden [IP: 52.40.89.93 443]
E: The repository 'https:
```

**Expected behavior**
Gauge should be installed successfully.

**Versions:**

 - OS linux/amd64 - https://hub.docker.com/layers/maven/library/maven/3.6.1-jdk-11/images/sha256-789d10276b20e1480838314fd13d687d60591fe1e867019c168611a3fb9a63a9?context=explore

**Additional context**

* local attempt on Windows 10 Windows Subsystem for Linux Ubuntu image: 
```
➜  ubuntuuser sudo gpg --no-default-keyring --keyring /usr/share/keyrings/gauge-archive-keyring.gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
[sudo] password for ubuntuuser:
gpg: keybox '/usr/share/keyrings/gauge-archive-keyring.gpg' created
gpg: failed to create temporary file '/home/ubuntuuser/.gnupg/.#lk0x00007fffd6719c50.DBHLT0010.59': No such file or directory
gpg: connecting dirmngr at '/home/ubuntuuser/.gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
➜  ubuntuuser sudo bash -c "echo deb [signed-by=/usr/share/keyrings/gauge-archive-keyring.gpg] https://dl.bintray.com/gauge/gauge-deb stable main > /etc/apt/sources.li
st.d/gauge.list"
➜  ubuntuuser sudo apt-get update && apt-get install gauge
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Err:4 https://dl.bintray.com/gauge/gauge-deb stable InRelease
  403  Forbidden [IP: 34.214.135.19 443]
Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1696 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2039 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [318 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [302 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [40.4 kB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1124 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [410 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [324 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [43.8 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1734 kB]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [253 kB]
Get:17 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [19.2 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [369 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [25.0 kB]
Reading package lists... Done
E: Failed to fetch https://dl.bintray.com/gauge/gauge-deb/dists/stable/InRelease  403  Forbidden [IP: 34.214.135.19 443]
E: The repository 'https://dl.bintray.com/gauge/gauge-deb stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
➜  ubuntuuser gauge -v
zsh: command not found: gauge
```

* pom.xml of java project
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.test</groupId>
    <artifactId>commerce-ui-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <webdrivermanager.version>3.3.0</webdrivermanager.version>
        <selenide.version>5.11.1</selenide.version>
        <selenium.version>3.141.59</selenium.version>
        <gauge-java.version>0.7.13</gauge-java.version>
        <assertj.version>3.6.2</assertj.version>
        <mailosaur.version>3.0.5</mailosaur.version>
        <sql2o.version>1.5.4</sql2o.version>
        <slf4j.version>1.7.25</slf4j.version>
        <mockito.version>2.17.0</mockito.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.thoughtworks.gauge</groupId>
            <artifactId>gauge-java</artifactId>
            <version>${gauge-java.version}</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>${webdrivermanager.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>logback-classic</artifactId>
                    <groupId>ch.qos.logback</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>${selenide.version}</version>
        </dependency>
        <!-- Assertion Library -->
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <!-- use 2.6.0 for Java 7 projects -->
            <version>${assertj.version}</version>
        </dependency>
        <!-- Database Connection -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.22</version>
        </dependency>
        <dependency>
            <groupId>org.sql2o</groupId>
            <artifactId>sql2o</artifactId>
            <version>${sql2o.version}</version>
        </dependency>
        <!-- Email Api -->
        <dependency>
            <groupId>com.mailosaur</groupId>
            <artifactId>mailosaur-java</artifactId>
            <version>${mailosaur.version}</version>
        </dependency>
        <!-- Logger -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <!-- Mocking Framework -->
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito.version}</version>
            <scope>test</scope>
        </dependency>
        <!-- Test Database -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.196</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>27.0.1-jre</version>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.10</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.21.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.thoughtworks.gauge.maven</groupId>
                <artifactId>gauge-maven-plugin</artifactId>
                <version>1.4.0</version>
                <executions>
                    <execution>
                        <phase>none</phase>
                        <configuration>
                            <specsDir>specs</specsDir>
                        </configuration>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>

```
